name: Localised Docs (testing)

on:
  schedule:
    - cron: '31 0 * * 0'
  workflow_dispatch:
    inputs:
      Locale:
        description: 'Locale to build'     
        required: true
        default: 'French'
        type: choice
        options:
          - French
          - Spanish
          - Portuguese
          - Czech
          - Chinese
          - Arabic
          - ALL

jobs:
  build:

    runs-on: ubuntu-20.04

    strategy:
      max-parallel: 1
      matrix:
        include:
          - id: French
            locale: fr
          - id: Spanish
            locale: es_419
          - id: Portuguese
            locale: pt
          - id: Czech
            locale: cs
          - id: Chinese
            locale: zh
          - id: Arabic
            locale: ar
      fail-fast: false

    # Updated if condition to handle workflow_dispatch
    if: (github.event_name == 'schedule') || (github.event_name == 'workflow_dispatch' && (github.event.inputs.Locale == 'ALL' || jobs.build.strategy.matrix.id == github.event.inputs.Locale))

    steps:
    - uses: actions/checkout@v2

    - name: Test variables with simple bash script
      shell: bash
      run: |
        echo "Param set: ${{ matrix.id }}"
        echo "Param set locale: ${{ matrix.locale }}"
        echo "DHI2_DOCS_LANGUAGE: ${{ env.DHIS2_DOCS_LANGUAGE }}"
        echo "SOURCE_DIR: ${{ env.SOURCE_DIR }}"
        echo "DEST_DIR: ${{ env.DEST_DIR }}"
      env:
        DHIS2_DOCS_LANGUAGE: '${{ matrix.locale }}'
        SOURCE_DIR: 'target/${{ matrix.locale }}/.'
        DEST_DIR: '${{ matrix.locale }}/'


