name: English - Single Page Test Build

on:
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Install custom pre-processor
      run: |
        cd tools/python/markdown-pp-master
        python3 setup.py develop
        pip install MarkdownPP

    - name: Install markdown extensions
      run: |
        cd tools/python/markdown-extensions/d_card
        python3 setup.py develop
        pip install d_card

    - name: Install dhis2_plugins for mkdocs
      run: |
        cd tools/python/dhis2_plugins
        python3 setup.py develop
        pip install dhis2_plugins

    - name: Install markdown hacks
      run: |
        # temporary hacks
        python3 -m site
        cp tools/python/blockprocessors.py ${pythonLocation}/lib/python3.8/site-packages/markdown/
        cp tools/python/attr_list.py ${pythonLocation}/lib/python3.8/site-packages/markdown/extensions/
        cp tools/python/tables.py ${pythonLocation}/lib/python3.8/site-packages/markdown/extensions/
        cp tools/python/search_index.py ${pythonLocation}/lib/python3.8/site-packages/mkdocs/contrib/search/

    - name: Install node
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: install prettier
      run: npm install -g prettier

    - name: Build the docs
      run: |
        mkdocs build --config-file mkdocs_single_page.yml
